
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analyzers;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int TK_comma = 16;
  public static final int TK_moda = 44;
  public static final int TK_string = 13;
  public static final int TK_end = 40;
  public static final int TK_sum = 19;
  public static final int TK_equal = 42;
  public static final int TK_arr = 15;
  public static final int TK_rbracket = 8;
  public static final int TK_max = 46;
  public static final int TK_console = 41;
  public static final int TK_var = 3;
  public static final int TK_histogram = 39;
  public static final int TK_lt = 11;
  public static final int TK_graphline = 35;
  public static final int TK_colon = 4;
  public static final int TK_res = 20;
  public static final int TK_exec = 34;
  public static final int TK_lparen = 17;
  public static final int TK_id = 9;
  public static final int TK_double = 5;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int TK_media = 24;
  public static final int TK_varianza = 45;
  public static final int TK_rparen = 18;
  public static final int TK_tituloy = 33;
  public static final int TK_titulox = 32;
  public static final int TK_label = 37;
  public static final int TK_char = 43;
  public static final int TK_column = 27;
  public static final int TK_print = 26;
  public static final int TK_semicolon = 14;
  public static final int TK_titulo = 29;
  public static final int TK_div = 22;
  public static final int TK_min = 47;
  public static final int TK_lbracket = 7;
  public static final int TK_double_v = 6;
  public static final int TK_mediana = 25;
  public static final int TK_ejey = 31;
  public static final int TK_program = 2;
  public static final int TK_graphpie = 36;
  public static final int TK_ejex = 30;
  public static final int TK_values = 38;
  public static final int TK_mul = 21;
  public static final int TK_mod = 23;
  public static final int TK_minus = 10;
  public static final int TK_graphbar = 28;
  public static final int TK_gt = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TK_program",
  "TK_var",
  "TK_colon",
  "TK_double",
  "TK_double_v",
  "TK_lbracket",
  "TK_rbracket",
  "TK_id",
  "TK_minus",
  "TK_lt",
  "TK_gt",
  "TK_string",
  "TK_semicolon",
  "TK_arr",
  "TK_comma",
  "TK_lparen",
  "TK_rparen",
  "TK_sum",
  "TK_res",
  "TK_mul",
  "TK_div",
  "TK_mod",
  "TK_media",
  "TK_mediana",
  "TK_print",
  "TK_column",
  "TK_graphbar",
  "TK_titulo",
  "TK_ejex",
  "TK_ejey",
  "TK_titulox",
  "TK_tituloy",
  "TK_exec",
  "TK_graphline",
  "TK_graphpie",
  "TK_label",
  "TK_values",
  "TK_histogram",
  "TK_end",
  "TK_console",
  "TK_equal",
  "TK_char",
  "TK_moda",
  "TK_varianza",
  "TK_max",
  "TK_min"
  };
}

