/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import Analyzers.token;
import Errores.Errores;
import Interface.Principal;
import static Interface.Principal.errorL;
import static Interface.Principal.errorS;
import static Interface.Principal.tableS;
import static Interface.Principal.lexemas;
import Tools.CreateReports;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author mesoi
 */
public class MReport extends javax.swing.JPanel {

    /**
     * Creates new form MReport
     */
    public MReport() {
        initComponents();

    }

    public void reporteErrores() {
        try {
            if (errorL.isEmpty() || errorS.isEmpty()) {
                JFrame framePadre = (JFrame) SwingUtilities.getWindowAncestor(this);
                JOptionPane.showMessageDialog(framePadre, "No existen errores", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            CreateReports.saveReportTok(CreateReports.ErrorsReport(errorL, errorS), "errores");
            JFrame framePadre = (JFrame) SwingUtilities.getWindowAncestor(this);
            JOptionPane.showMessageDialog(framePadre, "Reporte de Errores, generado exitosamente");
        } catch (IOException ex) {
            Logger.getLogger(MReport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void reporteTabla() {
        try {
            if (tableS == null) {
                JFrame framePadre = (JFrame) SwingUtilities.getWindowAncestor(this);
                JOptionPane.showMessageDialog(framePadre, "No existen variables analizadas", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            CreateReports.saveReportTok(CreateReports.symbolReport(tableS), "tabla");
            JFrame framePadre = (JFrame) SwingUtilities.getWindowAncestor(this);
            JOptionPane.showMessageDialog(framePadre, "Reporte de la tabla de Simbolos, generado exitosamente");
        } catch (IOException ex) {
            Logger.getLogger(MReport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void reporteTokens() {
        try {
            if (lexemas.isEmpty()) {
                JFrame framePadre = (JFrame) SwingUtilities.getWindowAncestor(this);
                JOptionPane.showMessageDialog(framePadre, "No existen lexemas leidos", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            CreateReports.saveReportTok(CreateReports.TokenReport(lexemas), "tokens");
            JFrame framePadre = (JFrame) SwingUtilities.getWindowAncestor(this);
            JOptionPane.showMessageDialog(framePadre, "Reporte de Tokens, generado exitosamente");
        } catch (IOException ex) {
            Logger.getLogger(MReport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new Components.PanelRound();
        btnErrores = new javax.swing.JButton();
        btnTokens = new javax.swing.JButton();
        btnTabla = new javax.swing.JButton();

        panelRound1.setBackground(new java.awt.Color(38, 40, 44));
        panelRound1.setAutoscrolls(true);
        panelRound1.setRoundBottomLeft(10);
        panelRound1.setRoundBottomRight(10);
        panelRound1.setRoundTopLeft(10);
        panelRound1.setRoundTopRight(10);

        btnErrores.setBackground(new java.awt.Color(38, 40, 44));
        btnErrores.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        btnErrores.setText("  Errores");
        btnErrores.setBorder(null);
        btnErrores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnErrores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnErroresActionPerformed(evt);
            }
        });

        btnTokens.setBackground(new java.awt.Color(38, 40, 44));
        btnTokens.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        btnTokens.setText("  Tokens");
        btnTokens.setBorder(null);
        btnTokens.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTokens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTokensActionPerformed(evt);
            }
        });

        btnTabla.setBackground(new java.awt.Color(38, 40, 44));
        btnTabla.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        btnTabla.setText("  Tabla de Simbolos");
        btnTabla.setBorder(null);
        btnTabla.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnErrores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addComponent(btnTokens, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnTokens, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnErroresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnErroresActionPerformed
        reporteErrores();
    }//GEN-LAST:event_btnErroresActionPerformed

    private void btnTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablaActionPerformed
        // TODO add your handling code here:
        reporteTabla();
    }//GEN-LAST:event_btnTablaActionPerformed

    private void btnTokensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTokensActionPerformed
        reporteTokens();
    }//GEN-LAST:event_btnTokensActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnErrores;
    private javax.swing.JButton btnTabla;
    private javax.swing.JButton btnTokens;
    private Components.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables
}
