/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Charts.Bar;

import Charts.Bar.blankchart.BlankPlotChart;
import Charts.Bar.blankchart.BlankPlotChatRender;
import Charts.Bar.blankchart.SeriesSize;
import java.awt.Color;

import java.awt.Graphics2D;
import java.awt.event.MouseEvent;
import java.awt.geom.Path2D;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author mesoi
 */
public class Chart extends javax.swing.JPanel {

    /**
     * Creates new form Chart
     */
    private List<ModelLegend> legends = new ArrayList<>();
    private List<ModelLegend> legendsLeft = new ArrayList<>();
    private List<ModelChart> model = new ArrayList<>();
    private final int seriesSize = 10;
    private final int seriesSpace = 5;

    public Chart() {
        initComponents();

        blankPlotChart.setBlankPlotChatRender(new BlankPlotChatRender() {
            @Override
            public String getLabelText(int index) {
                return model.get(index).getLabel();
            }

            @Override
            public void renderSeries(BlankPlotChart chart, Graphics2D g2, SeriesSize size, int index) {
                int newBarWidth = 20; // Ajusta este valor según lo que necesites

                // Calcular el nuevo ancho total de todas las series
                double totalSeriesWidth = (newBarWidth * legends.size()) + (seriesSpace * (legends.size() - 1));

                // Calcular la nueva posición inicial para centrar las barras
                double x = (size.getWidth() - totalSeriesWidth) / 2;

                for (int i = 0; i < legends.size(); i++) {
                    ModelLegend legend = legends.get(i);
                    g2.setColor(legend.getColor());

                    // Obtener el valor de la serie y escalarlo al tamaño de la gráfica
                    double seriesValues = chart.getSeriesValuesOf(model.get(index).getValues()[i], size.getHeight());

                    // Dibujar la barra con el nuevo grosor y la nueva posición x
                    g2.fillRect((int) (size.getX() + x),
                            (int) (size.getY() + size.getHeight() - seriesValues),
                            newBarWidth, // Usar el nuevo grosor
                            (int) seriesValues);

                    // Mover la posición x para la siguiente serie
                    x += seriesSpace + newBarWidth; // Ajustar en función del espacio entre barras
                }
            }
        });

    }

    public void setTitle(String Title) {
        lblTitle.setText(Title);
    }

    public void addLegend(String name, Color color) {
        ModelLegend data = new ModelLegend(name, color);
        legends.add(data);
        panelLegendB.add(new LegendItem(data));
        panelLegendB.repaint();
        panelLegendB.revalidate();
    }

    public void addLegendLeft(String name, Color color) {
        ModelLegend data = new ModelLegend(name, color);
        legendsLeft.add(data);
        panelLegendR.add(new LegendItemLeft(data));
        panelLegendR.repaint();
        panelLegendR.revalidate();
    }

    public void addData(ModelChart data) {
        model.add(data);
        blankPlotChart.setLabelCount(model.size());
        double max = data.getMaxValues();
        if (max > blankPlotChart.getMaxValues()) {
            blankPlotChart.setMaxValues(max);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        panelLegendB = new javax.swing.JPanel();
        panelLegendR = new javax.swing.JPanel();
        blankPlotChart = new Charts.Bar.blankchart.BlankPlotChart();

        setOpaque(false);

        jPanel1.setOpaque(false);

        lblTitle.setFont(new java.awt.Font("Montserrat Black", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitle.setText("Titulo");

        panelLegendB.setOpaque(false);
        panelLegendB.setLayout(new java.awt.GridBagLayout());

        panelLegendR.setOpaque(false);
        java.awt.GridBagLayout panelLegendRLayout = new java.awt.GridBagLayout();
        panelLegendRLayout.columnWidths = new int[] {10};
        panelLegendRLayout.rowHeights = new int[] {10};
        panelLegendRLayout.columnWeights = new double[] {10.0};
        panelLegendRLayout.rowWeights = new double[] {10.0};
        panelLegendR.setLayout(panelLegendRLayout);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelLegendB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(panelLegendR, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blankPlotChart, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelLegendR, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(blankPlotChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLegendB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Charts.Bar.blankchart.BlankPlotChart blankPlotChart;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelLegendB;
    private javax.swing.JPanel panelLegendR;
    // End of variables declaration//GEN-END:variables
}
