/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Charts.Bar;

import java.awt.Color;

/**
 *
 * @author mesoi
 */
public class LegendItemLeft extends javax.swing.JPanel {

    /**
     * Creates new form LegendItem
     */
    public LegendItemLeft(ModelLegend data) {
        initComponents();
        setOpaque(false);
        lbColor.setBackground(data.getColor());
        rotatedLabel2.setTextAndAngle(data.getName(),270);
        rotatedLabel2.setForeground(new Color(162,163,165));
        rotatedLabel2.setFont(new java.awt.Font("Montserrat Medium", 0, 16));
    }
    
    public LegendItemLeft(Charts.Line.ModelLegend data) {
        initComponents();
        setOpaque(false);
        lbColor.setBackground(data.getColor());
        rotatedLabel2.setTextAndAngle(data.getName(),270);
        rotatedLabel2.setForeground(new Color(162,163,165));
        rotatedLabel2.setFont(new java.awt.Font("Montserrat Medium", 0, 16));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotatedLabel1 = new Charts.Bar.RotatedLabel();
        lbColor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rotatedLabel2 = new Charts.Bar.RotatedLabel();

        rotatedLabel1.setText("rotatedLabel1");

        jLabel1.setText(" ");

        rotatedLabel2.setBackground(new java.awt.Color(102, 102, 255));
        rotatedLabel2.setForeground(new java.awt.Color(153, 153, 255));
        rotatedLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rotatedLabel2.setText("Texo de Prueba");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rotatedLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lbColor, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbColor, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rotatedLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbColor;
    private Charts.Bar.RotatedLabel rotatedLabel1;
    private Charts.Bar.RotatedLabel rotatedLabel2;
    // End of variables declaration//GEN-END:variables
}
